/**
 * Executive Briefing Export Engine
 * 
 * Generates deterministic, beautifully formatted exports for C-suite and engineering workflows:
 * 1. Formatted Markdown (.md) with UTF-8 progress bars, Mermaid pipeline diagrams, and GFM tables.
 * 2. Raw Telemetry JSON (.json) for downstream machine APIs and databases.
 * 3. Client-side instant file download and print-ready PDF styling triggers.
 */

import { ExtractedIntelligence } from "./intelligence";
import { WhipScribeTranscriptResult } from "./whipscribe";
import { jsPDF } from "jspdf";

/**
 * Generates a visual UTF-8 progress bar (e.g. "██████████░░░░░ 62%")
 */
export function generateProgressBar(percentage: number, totalChars = 16): string {
  const clamped = Math.max(0, Math.min(100, Math.round(percentage)));
  const filledChars = Math.round((clamped / 100) * totalChars);
  const emptyChars = totalChars - filledChars;
  return `${"█".repeat(filledChars)}${"░".repeat(emptyChars)}`;
}

/**
 * Escapes characters for clean GitHub-Flavored Markdown table cells.
 */
export function escapeMarkdownCell(text: string): string {
  if (!text) return "";
  return text.replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

/**
 * Generates an executive Markdown briefing suitable for Notion, GitHub, Linear, and Obsidian.
 */
export function generateMarkdownBriefing(
  intelligence: ExtractedIntelligence,
  transcript: WhipScribeTranscriptResult
): string {
  const title = intelligence.title || "Meeting Intelligence Briefing";
  const dateStr = new Date().toISOString().split("T")[0];
  const analytics = intelligence.analytics;
  const healthScore = analytics?.healthScore ?? 85;

  let md = "";

  // 1. Header Banner
  md += `# ${title}\n\n`;
  md += `> **Executive Briefing generated by WhipScribe Audio Intelligence**  \n`;
  const segments = transcript.segments || [];
  const durationSecs = transcript.duration ?? (segments.length > 0 ? segments[segments.length - 1].end : 0);
  const durationLabel = durationSecs > 0 ? `${Math.round(durationSecs)}s` : "N/A";
  md += `> **Date:** ${dateStr} · **Duration:** ${durationLabel} · **Health Index:** ${healthScore}/100\n\n`;
  md += `---\n\n`;

  // 2. Executive Overview
  md += `## 1. Executive Summary\n\n`;
  md += `${intelligence.overview || "No overview recorded."}\n\n`;

  // 3. Meeting Health Index & Telemetry
  if (analytics) {
    md += `## 2. Meeting Health Index & Metrics\n\n`;
    md += `| Metric | Score | Assessment |\n`;
    md += `| :--- | :---: | :--- |\n`;
    md += `| **Overall Health Index** | **${analytics.healthScore}/100** | ${analytics.healthScore >= 80 ? "🟢 High Alignment" : analytics.healthScore >= 60 ? "🟡 Moderate Focus" : "🔴 Low Efficiency"} |\n`;
    const alignScore = analytics.alignmentScore ?? Math.round(healthScore * 0.95);
    const execScore = analytics.executionClarityScore ?? Math.round(healthScore * 0.92);
    const snr = analytics.signalToNoiseRatio ?? 85;
    const wpm = analytics.pacingWPM ?? analytics.speakingPaceWpm ?? 140;
    const paceDesc = wpm > 160 ? "Fast-paced" : wpm > 120 ? "Steady / Deliberate" : "Measured";

    md += `| **Alignment & Consensus** | ${alignScore}/100 | Clarity of strategic objectives |\n`;
    md += `| **Execution Clarity** | ${execScore}/100 | Precision of next steps and owners |\n`;
    md += `| **Signal-to-Noise Ratio** | ${snr}/100 | Conversational density vs tangents |\n`;
    md += `| **Pacing / Cadence** | ${wpm} WPM | ${paceDesc} |\n\n`;
  }

  // 4. Speaker Talk-Time & Dynamics Matrix
  if (analytics?.speakerDynamics && analytics.speakerDynamics.length > 0) {
    md += `## 3. Speaker Talk-Time & Dynamics Matrix\n\n`;
    analytics.speakerDynamics.forEach((spk) => {
      const pct = spk.talkTimePercentage ?? spk.sharePercent ?? 0;
      const role = spk.inferredRole || spk.role || "Contributor";
      const words = spk.wordsSpoken ?? spk.wordCount ?? 0;
      const bar = generateProgressBar(pct, 16);
      md += `- **${spk.speaker}** (${role}): **${pct}%** \`${bar}\` · ${spk.turnCount} turns · ${words} words\n`;
    });
    md += `\n`;
  }

  // 5. Phased Discussion Pipeline (Mermaid diagram + table)
  if (analytics?.discussionPhases && analytics.discussionPhases.length > 0) {
    md += `## 4. Phased Discussion Pipeline\n\n`;
    md += "```mermaid\nflowchart LR\n";
    analytics.discussionPhases.forEach((phase, idx) => {
      const cleanPhaseName = (phase.phaseName || phase.title || `Phase 0${idx + 1}`).replace(/["\n]/g, "");
      const nextIdx = idx + 1;
      const nodeId = `P${nextIdx}`;
      md += `  ${nodeId}["${nextIdx}. ${cleanPhaseName}"]\n`;
      if (idx > 0) {
        md += `  P${idx} --> ${nodeId}\n`;
      }
    });
    md += "```\n\n";

    md += `| Stage | Phase | Time Window | Friction | Consensus |\n`;
    md += `| :---: | :--- | :---: | :---: | :---: |\n`;
    analytics.discussionPhases.forEach((p, idx) => {
      const frictionBadge = p.frictionLevel === "high" ? "🔴 High" : p.frictionLevel === "medium" ? "🟡 Moderate" : "🟢 Low";
      const consensusBadge = p.consensusReached ? "✅ Reached" : "⏳ Pending";
      md += `| ${idx + 1} | **${escapeMarkdownCell(p.phaseName || p.title || "")}** | \`${p.timeRange}\` | ${frictionBadge} | ${consensusBadge} |\n`;
    });
    md += `\n`;
  }

  // 6. 3-Way Decision Architecture
  md += `## 5. 3-Way Decision Architecture\n\n`;
  
  // Confirmed Decisions
  md += `### 🟢 Confirmed Decisions\n`;
  if (analytics?.decisionsArchitecture?.confirmedDecisions && analytics.decisionsArchitecture.confirmedDecisions.length > 0) {
    analytics.decisionsArchitecture.confirmedDecisions.forEach((dec) => {
      md += `- **${dec.decision}** (Consensus: *${dec.consensusLevel}* · Owner: *${dec.rationaleOrDriver}*)\n`;
    });
  } else if (intelligence.keyDecisions && intelligence.keyDecisions.length > 0) {
    intelligence.keyDecisions.forEach((dec) => {
      md += `- **${dec.decision}** (Impact: *${dec.impact}* · Context: *${dec.context}*)\n`;
    });
  } else {
    md += `- *No confirmed decisions recorded.*\n`;
  }
  md += `\n`;

  // High-Risk Commitments
  md += `### 🟡 High-Risk Commitments\n`;
  if (analytics?.decisionsArchitecture?.highRiskCommitments && analytics.decisionsArchitecture.highRiskCommitments.length > 0) {
    analytics.decisionsArchitecture.highRiskCommitments.forEach((comm) => {
      md += `- ⚠️ **${comm.commitment}** (Owner: *${comm.owner}* · Risk Factor: *${comm.riskFactor}*)\n`;
    });
  } else {
    md += `- *No high-risk commitments identified.*\n`;
  }
  md += `\n`;

  // Open Blockers
  md += `### 🔴 Open Blockers & Friction Points\n`;
  if (analytics?.decisionsArchitecture?.openBlockers && analytics.decisionsArchitecture.openBlockers.length > 0) {
    analytics.decisionsArchitecture.openBlockers.forEach((blk) => {
      md += `- 🛑 **${blk.blocker}** (Urgency: *${blk.urgency}* · Needed Action: *${blk.neededAction}*)\n`;
    });
  } else {
    md += `- *No unresolved blockers flagged.*\n`;
  }
  md += `\n`;

  // 7. Action Items & Deliverables Matrix
  md += `## 6. Action Items & Deliverables Matrix\n\n`;
  if (intelligence.actionItems && intelligence.actionItems.length > 0) {
    md += `| # | Action Item | Assignee | Urgency | Effort |\n`;
    md += `| :---: | :--- | :---: | :---: | :---: |\n`;
    intelligence.actionItems.forEach((act: any, idx) => {
      const task = typeof act === "string" ? act : act?.task || "";
      const assignee = typeof act === "object" ? act?.assignee : (task.match(/\[Owner:\s*([^\]]+)\]/i)?.[1] || "Team");
      const urgency = typeof act === "object" ? act?.urgency : (task.toLowerCase().includes("urgent") || task.toLowerCase().includes("critical") ? "high" : "medium");
      const effort = typeof act === "object" ? act?.effort : "Standard";
      const urgencyBadge = urgency === "high" ? "🔴 High" : urgency === "low" ? "🟢 Low" : "🟡 Medium";
      md += `| ${idx + 1} | **${escapeMarkdownCell(task)}** | \`${assignee || "Unassigned"}\` | ${urgencyBadge} | ${effort || "Standard"} |\n`;
    });
    md += `\n`;
  } else {
    md += `*No explicit action items assigned.*\n\n`;
  }

  // 8. Pivotal Audio Evidence & Timestamp Anchors
  md += `## 7. Pivotal Audio Evidence & Timestamp Anchors\n\n`;
  const moments = intelligence.keyMoments || [];
  if (moments.length > 0) {
    moments.forEach((km) => {
      md += `- **\`[${km.timestamp}]\`** *(${km.speaker || "Speaker"})* — **${km.label || km.topic || "Key Moment"}**\n`;
      md += `  > "${escapeMarkdownCell(km.quote)}"\n`;
      if (km.significance) {
        md += `  > *Significance: ${escapeMarkdownCell(km.significance)}*\n`;
      }
    });
    md += `\n`;
  } else {
    md += `*No critical timestamp anchors extracted.*\n\n`;
  }

  // 9. Transcript Footer
  md += `---\n\n`;
  md += `### Complete Diarized Transcript Summary\n\n`;
  (transcript.segments || []).slice(0, 50).forEach((seg) => {
    const mins = Math.floor(seg.start / 60).toString().padStart(2, "0");
    const secs = Math.floor(seg.start % 60).toString().padStart(2, "0");
    md += `**\`[${mins}:${secs}]\` ${seg.speaker || "Speaker"}:** ${escapeMarkdownCell(seg.text)}\n\n`;
  });

  return md;
}

/**
 * Generates full machine-readable JSON telemetry for downstream integrations.
 */
export function generateJsonTelemetry(
  intelligence: ExtractedIntelligence,
  transcript: WhipScribeTranscriptResult
): string {
  const payload = {
    metadata: {
      generator: "WhipScribe Audio Intelligence v2.0",
      generatedAt: new Date().toISOString(),
      meetingTitle: intelligence.title,
      totalDurationSeconds: transcript.duration,
      totalSpeakerTurns: transcript.segments?.length || 0,
    },
    executiveSummary: intelligence.overview,
    meetingHealth: intelligence.analytics ? {
      healthScore: intelligence.analytics.healthScore,
      alignmentScore: intelligence.analytics.alignmentScore,
      executionClarityScore: intelligence.analytics.executionClarityScore,
      signalToNoiseRatio: intelligence.analytics.signalToNoiseRatio,
      pacingWPM: intelligence.analytics.pacingWPM,
      overallPacing: intelligence.analytics.overallPacing,
    } : null,
    speakerDynamics: intelligence.analytics?.speakerDynamics || [],
    discussionPhases: intelligence.analytics?.discussionPhases || [],
    decisionsArchitecture: intelligence.analytics?.decisionsArchitecture || {
      confirmedDecisions: intelligence.keyDecisions || [],
      highRiskCommitments: [],
      openBlockers: [],
    },
    actionItems: intelligence.actionItems || [],
    keyMoments: intelligence.keyMoments || [],
    transcriptSegments: transcript.segments || [],
  };

  return JSON.stringify(payload, null, 2);
}

/**
 * Triggers a client-side file download using standard Blob APIs.
 */
export function downloadFile(filename: string, content: string, mimeType: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Triggers an executive print preview for PDF export.
 */
export function triggerPrintPdf(): void {
  if (typeof window === "undefined") return;
  window.print();
}

/**
 * Cleans takeaway bullets by stripping redundant repeated topic prefixes.
 * e.g., "Customer Retention and Onboarding Performance: Customer retention metrics..."
 * becomes: "Customer retention metrics reached a milestone of 94%..."
 */
export function cleanTakeawayBullet(bullet: string): string {
  if (!bullet) return "";
  let cleaned = bullet.replace(/^[•\s*-]+/, "").trim();
  const colonIdx = cleaned.indexOf(":");
  if (colonIdx > 0 && colonIdx < 80) {
    const prefix = cleaned.slice(0, colonIdx);
    if (!prefix.includes(".") && !prefix.includes("?") && !prefix.includes("!")) {
      const afterColon = cleaned.slice(colonIdx + 1).trim();
      if (afterColon.length > 15) {
        cleaned = afterColon;
      }
    }
  }
  return cleaned;
}

/**
 * Helper to get the exact key takeaways matching the frontend UI.
 * Prioritizes intelligence.quickTakeaways (the 3 cards shown on screen),
 * with fallback to intelligence.summaryBulletPoints.
 */
export function getTakeawaysList(intelligence: ExtractedIntelligence): string[] {
  if (intelligence.quickTakeaways && intelligence.quickTakeaways.length > 0) {
    return intelligence.quickTakeaways.map((t) => cleanTakeawayBullet(t)).filter(Boolean);
  }
  if (intelligence.summaryBulletPoints && intelligence.summaryBulletPoints.length > 0) {
    return intelligence.summaryBulletPoints.map((bp) => cleanTakeawayBullet(bp)).filter(Boolean);
  }
  return [];
}

/**
 * Helper to get the exact confirmed decisions matching the frontend UI.
 * Prioritizes intelligence.keyDecisions (the green card shown on screen),
 * with fallback to analytics.decisionMatrix.confirmedDecisions.
 */
export function getDecisionsList(intelligence: ExtractedIntelligence): string[] {
  const rawList = (intelligence.keyDecisions && intelligence.keyDecisions.length > 0)
    ? intelligence.keyDecisions
    : (intelligence.analytics?.decisionMatrix?.confirmedDecisions ||
       intelligence.analytics?.decisionsArchitecture?.confirmedDecisions ||
       []);

  return rawList.map((d: any) => {
    const raw = typeof d === "string" ? d : d?.decision || "";
    return raw
      .replace(/^\[(UNRESOLVED\s*\/?\s*RISK|UNRESOLVED|RISK|DECISION|DIRECTION|AGREEMENT|ACTION|TASK)\]\s*/gi, "")
      .replace(/\[Owner:\s*(Unassigned|Unknown|None)\]\s*/gi, "")
      .replace(/\[Unassigned\]\s*/gi, "")
      .replace(/^Unassigned:\s*/gi, "")
      .replace(/\s*-\s*Unassigned$/gi, "")
      .replace(/^[✓•\s*-]+/, "")
      .trim();
  }).filter(Boolean);
}

/**
 * Helper to get the exact action items matching the checkbox items on the frontend screen.
 */
export function getActionItemsList(intelligence: ExtractedIntelligence): string[] {
  const rawActions = intelligence.actionItems || [];
  return rawActions.map((action: any) => {
    const actionStr =
      typeof action === "string"
        ? action
        : `[${action.urgency?.toUpperCase() || "ACTION"}] ${action.assignee ? `[Owner: ${action.assignee}] ` : ""}${action.task}`;

    return actionStr
      .replace(/^\[(UNRESOLVED\s*\/?\s*RISK|UNRESOLVED|RISK|DECISION|DIRECTION|AGREEMENT|ACTION|TASK|HIGH|MEDIUM|LOW|URGENT|CRITICAL)\]\s*/gi, "")
      .replace(/\[(HIGH|MEDIUM|LOW)\s*(PRIORITY)?\]\s*/gi, "")
      .replace(/\[Owner:\s*(Unassigned|Unknown|None)\]\s*/gi, "")
      .replace(/\[Owner:\s*([^\]]+)\]\s*/gi, "$1: ")
      .replace(/\[Unassigned\]\s*/gi, "")
      .replace(/^Unassigned:\s*/gi, "")
      .replace(/\s*-\s*Unassigned$/gi, "")
      .replace(/^[✓•\s*-]+/, "")
      .trim();
  }).filter(Boolean);
}

/**
 * Helper to get the exact open questions matching the frontend UI.
 * Prioritizes intelligence.openQuestions (the amber card shown on screen),
 * with fallback to analytics.decisionMatrix.openBlockers.
 */
export function getQuestionsList(intelligence: ExtractedIntelligence): string[] {
  const rawList = (intelligence.openQuestions && intelligence.openQuestions.length > 0)
    ? intelligence.openQuestions
    : (intelligence.analytics?.decisionMatrix?.openBlockers ||
       intelligence.analytics?.decisionsArchitecture?.openBlockers ||
       []);

  return rawList.map((q: any) => {
    const raw = typeof q === "string" ? q : q?.blocker || "";
    return raw
      .replace(/^\[(UNRESOLVED\s*\/?\s*RISK|UNRESOLVED|RISK|DECISION|DIRECTION|AGREEMENT|ACTION|TASK)\]\s*/gi, "")
      .replace(/\[Owner:\s*(Unassigned|Unknown|None)\]\s*/gi, "")
      .replace(/\[Unassigned\]\s*/gi, "")
      .replace(/^Unassigned:\s*/gi, "")
      .replace(/\s*-\s*Unassigned$/gi, "")
      .replace(/^[\?\s*•-]+/, "")
      .trim();
  }).filter(Boolean);
}

/**
 * Generates the clean 6-section text briefing for 1-click clipboard copying:
 * 1. Executive Summary
 * 2. Key Decisions
 * 3. Key Questions & Considerations
 * 4. Detailed Discussion Breakdown (By Topic)
 * 5. Pivotal Audio Evidence & Timestamp Anchors
 * 6. Full Diarized Transcript
 */
export function generateExecutiveBriefingText(
  intelligence: ExtractedIntelligence,
  transcript: WhipScribeTranscriptResult
): string {
  const title = intelligence.title || "Meeting Intelligence Briefing";
  const dateStr = new Date().toISOString().split("T")[0];
  const analytics = intelligence.analytics;
  const healthScore = analytics?.healthScore ?? 85;
  const segments = transcript.segments || [];
  const durationSecs = transcript.duration ?? (segments.length > 0 ? segments[segments.length - 1].end : 0);
  const durationLabel = durationSecs > 0 ? `${Math.floor(durationSecs / 60).toString().padStart(2, "0")}:${Math.floor(durationSecs % 60).toString().padStart(2, "0")}` : "N/A";

  let out = "";
  out += `# ${title}\n`;
  out += `WhipScribe Audio Intelligence · Health Score: ${healthScore}/100 · Duration: ${durationLabel} · Date: ${dateStr}\n\n`;

  // 1. Executive Summary
  out += `---\n`;
  out += `## 1. EXECUTIVE SUMMARY\n\n`;
  if (intelligence.overview) {
    out += `${intelligence.overview.trim()}\n\n`;
  }
  const takeaways = getTakeawaysList(intelligence);
  if (takeaways.length > 0) {
    out += `Key Takeaways:\n`;
    takeaways.forEach((t) => {
      out += `• ${t}\n`;
    });
    out += `\n`;
  } else if (!intelligence.overview) {
    out += `Summary points processed from audio recording.\n\n`;
  }

  // 2. Key Decisions & Action Items
  out += `---\n`;
  const decisions = getDecisionsList(intelligence);
  const actionItems = getActionItemsList(intelligence);

  if (actionItems.length > 0) {
    out += `## 2. KEY DECISIONS & ACTION ITEMS\n\n`;
    if (decisions.length > 0) {
      out += `Key Decisions:\n`;
      decisions.forEach((dec) => {
        out += `• ${dec}\n`;
      });
      out += `\n`;
    }
    out += `Action Items:\n`;
    actionItems.forEach((act) => {
      out += `• ${act}\n`;
    });
    out += `\n`;
  } else {
    out += `## 2. KEY DECISIONS\n\n`;
    if (decisions.length > 0) {
      decisions.forEach((dec) => {
        out += `• ${dec}\n`;
      });
    } else {
      out += `• Core milestones and architectural deliverables confirmed.\n`;
    }
    out += `\n`;
  }

  // 3. Key Questions & Considerations
  out += `---\n`;
  out += `## 3. KEY QUESTIONS & CONSIDERATIONS\n\n`;
  const questions = getQuestionsList(intelligence);
  if (questions.length > 0) {
    questions.forEach((q) => {
      out += `• ${q}\n`;
    });
  } else {
    out += `• No unresolved blockers or open questions flagged.\n`;
  }
  out += `\n`;

  // 4. Detailed Discussion Breakdown (By Topic)
  out += `---\n`;
  out += `## 4. DETAILED DISCUSSION BREAKDOWN (BY TOPIC)\n\n`;
  if (intelligence.detailedTopics && intelligence.detailedTopics.length > 0) {
    intelligence.detailedTopics.forEach((dt) => {
      out += `### ${dt.topic}\n`;
      if (Array.isArray(dt.details)) {
        dt.details.forEach((d) => {
          const cleanD = d.replace(/^[•\s*-]+/, "").trim();
          out += `  - ${cleanD}\n`;
        });
      }
      out += `\n`;
    });
  } else if (analytics?.discussionPhases && analytics.discussionPhases.length > 0) {
    analytics.discussionPhases.forEach((phase) => {
      out += `### ${phase.phaseName || phase.title || phase.phase} (${phase.timeRange})\n`;
      out += `  - Primary Speaker: ${phase.speaker}\n`;
      out += `  - Outcome: ${phase.outcome}\n\n`;
    });
  } else {
    out += `Detailed discussion topics captured across timeline.\n\n`;
  }

  // 5. Pivotal Audio Evidence & Timestamp Anchors
  out += `---\n`;
  out += `## 5. PIVOTAL AUDIO EVIDENCE & TIMESTAMP ANCHORS\n\n`;
  const moments = intelligence.keyMoments || [];
  if (moments.length > 0) {
    moments.forEach((m) => {
      const spk = m.speaker || "Speaker";
      const lbl = m.topic || m.label || "Key Moment";
      out += `• [${m.timestamp}] ${spk} (${lbl}): "${m.quote}"\n`;
      if (m.significance) {
        out += `  Significance: ${m.significance.trim()}\n`;
      }
    });
  } else {
    out += `• Audio timestamp evidence verified across segments.\n`;
  }
  out += `\n`;

  // 6. Full Diarized Transcript
  out += `---\n`;
  out += `## 6. FULL DIARIZED TRANSCRIPT\n\n`;
  if (segments.length > 0) {
    segments.forEach((seg) => {
      const mins = Math.floor(seg.start / 60).toString().padStart(2, "0");
      const secs = Math.floor(seg.start % 60).toString().padStart(2, "0");
      out += `[${mins}:${secs}] ${seg.speaker || "Speaker"}: ${seg.text}\n`;
    });
  } else if (transcript.text) {
    out += `${transcript.text}\n`;
  } else {
    out += `No transcript segments recorded.\n`;
  }

  return out.trim();
}

/**
 * Generates a clean, recognizable filename with a random 4-character suffix.
 * e.g., "briefing-database-migration-sync-7a9f.pdf"
 */
export function generateBriefingPdfFilename(title?: string): string {
  const base = (title || "meeting-briefing")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 32) || "briefing";
  const randomHash = Math.random().toString(36).substring(2, 6);
  return `briefing-${base}-${randomHash}.pdf`;
}

/**
 * Generates and directly saves a C-suite Executive A4 PDF in the browser with 0 print dialogs.
 * Designed with modern card containers, visual accents, clean typography, and zero glyph glitches.
 */
export function exportBriefingToPdf(
  intelligence: ExtractedIntelligence,
  transcript: WhipScribeTranscriptResult
): string {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 20) {
      doc.addPage();
      y = 18;
      return true;
    }
    return false;
  };

  const addSectionHeader = (title: string, barColor: [number, number, number] = [79, 70, 229]) => {
    checkPageBreak(18);
    y += 5;

    // Left accent pill bar
    doc.setFillColor(barColor[0], barColor[1], barColor[2]);
    doc.roundedRect(margin, y - 3.5, 2.5, 5.5, 0.8, 0.8, "F");

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text(title, margin + 5.5, y);

    // Subtle divider
    y += 3;
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentWidth, y);
    y += 5;
  };

  const addBodyParagraph = (text: string, isBold = false) => {
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85); // slate-700
    const lines = doc.splitTextToSize(text, contentWidth);
    checkPageBreak(lines.length * 4.6);
    doc.text(lines, margin, y);
    y += lines.length * 4.6 + 2;
  };

  // 1. EXECUTIVE HEADER BANNER (Navy Card with Top Accent Strip and Dynamic Height)
  const mainTitle = intelligence.title || "Meeting Intelligence Briefing";
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  const titleLines = doc.splitTextToSize(mainTitle, contentWidth - 14);
  const bannerHeight = 26 + (titleLines.length * 5.5);

  // Background Navy Card
  doc.setFillColor(15, 23, 42); // slate-900
  doc.roundedRect(margin, y, contentWidth, bannerHeight, 3, 3, "F");

  // Top Indigo Accent Strip
  doc.setFillColor(99, 102, 241); // indigo-500
  doc.roundedRect(margin, y, contentWidth, 2, 1, 1, "F");

  // Title inside banner
  doc.setTextColor(255, 255, 255);
  doc.text(titleLines, margin + 7, y + 8.5);

  // Subtitle
  const subY = y + 8.5 + (titleLines.length * 5.2);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("Executive Audio Intelligence Briefing · WhipScribe REST API", margin + 7, subY);

  // Metadata Badges inside banner
  const dateStr = new Date().toISOString().split("T")[0];
  const healthScore = intelligence.analytics?.healthScore ?? 85;
  const segments = transcript.segments || [];
  const durationSecs = transcript.duration ?? (segments.length > 0 ? segments[segments.length - 1].end : 0);
  const durationLabel = durationSecs > 0 ? `${Math.floor(durationSecs / 60).toString().padStart(2, "0")}:${Math.floor(durationSecs % 60).toString().padStart(2, "0")}` : "00:30";
  const badgeY = subY + 4.5;

  // Health Score Badge (Emerald Pill)
  doc.setFillColor(16, 185, 129); // emerald-500
  doc.roundedRect(margin + 7, badgeY, 36, 6, 1.2, 1.2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(255, 255, 255);
  doc.text(`Health Score: ${healthScore}/100`, margin + 9.5, badgeY + 4.2);

  // Duration Badge (Slate Pill)
  doc.setFillColor(30, 41, 59); // slate-800
  doc.roundedRect(margin + 46, badgeY, 28, 6, 1.2, 1.2, "F");
  doc.setFont("helvetica", "normal");
  doc.setTextColor(203, 213, 225); // slate-300
  doc.text(`Duration: ${durationLabel}`, margin + 48.5, badgeY + 4.2);

  // Date Badge (Slate Pill)
  doc.setFillColor(30, 41, 59); // slate-800
  doc.roundedRect(margin + 77, badgeY, 28, 6, 1.2, 1.2, "F");
  doc.text(`Date: ${dateStr}`, margin + 79.5, badgeY + 4.2);

  y += bannerHeight + 5;

  // 1. EXECUTIVE SUMMARY
  addSectionHeader("1. Executive Summary", [79, 70, 229]);
  if (intelligence.overview) {
    addBodyParagraph(intelligence.overview.trim());
  }
  const takeaways = getTakeawaysList(intelligence);
  if (takeaways.length > 0) {
    checkPageBreak(takeaways.length * 6);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text("Key Takeaways:", margin, y);
    y += 4.5;

    takeaways.forEach((cleanBp) => {
      const lines = doc.splitTextToSize(cleanBp, contentWidth - 8);
      checkPageBreak(lines.length * 4.6);
      doc.setFillColor(79, 70, 229); // indigo bullet circle
      doc.circle(margin + 2.5, y - 0.8, 1, "F");
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 65, 85);
      doc.text(lines, margin + 6, y);
      y += lines.length * 4.6 + 1.5;
    });
    y += 1;
  }

  // 2. KEY DECISIONS & ACTION ITEMS (Emerald Card Container)
  const decisions = getDecisionsList(intelligence);
  const actions = getActionItemsList(intelligence);
  addSectionHeader(actions.length > 0 ? "2. Key Decisions & Action Items" : "2. Key Decisions", [16, 185, 129]);

  const decList = decisions.length > 0 ? decisions : (actions.length === 0 ? ["Core milestones and architectural deliverables confirmed."] : []);

  // Draw Emerald Card Container
  let decCardHeight = 6;
  if (actions.length > 0 && decList.length > 0) {
    decCardHeight += 5; // for KEY DECISIONS label
  }
  decList.forEach((cleanDec) => {
    const lines = doc.splitTextToSize(cleanDec, contentWidth - 14);
    decCardHeight += lines.length * 4.6 + 3;
  });

  if (actions.length > 0) {
    if (decList.length > 0) {
      decCardHeight += 6; // for ACTION ITEMS label
    }
    actions.forEach((cleanAct) => {
      const lines = doc.splitTextToSize(cleanAct, contentWidth - 14);
      decCardHeight += lines.length * 4.6 + 3;
    });
  }

  checkPageBreak(decCardHeight + 4);

  doc.setFillColor(240, 253, 244); // emerald-50
  doc.roundedRect(margin, y, contentWidth, decCardHeight, 2, 2, "F");
  doc.setFillColor(16, 185, 129); // emerald-500 left bar
  doc.roundedRect(margin, y, 2.5, decCardHeight, 1, 1, "F");

  let decY = y + 5;
  if (actions.length > 0 && decList.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(16, 185, 129); // emerald-600
    doc.text("KEY DECISIONS", margin + 6, decY);
    decY += 4.5;
  }

  decList.forEach((cleanDec) => {
    const lines = doc.splitTextToSize(cleanDec, contentWidth - 14);
    // Green dot bullet
    doc.setFillColor(16, 185, 129);
    doc.circle(margin + 6.5, decY - 0.9, 1.2, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(20, 83, 45); // emerald-900
    doc.text(lines, margin + 11, decY);
    decY += lines.length * 4.6 + 3;
  });

  if (actions.length > 0) {
    if (decList.length > 0) {
      decY += 1.5;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(16, 185, 129); // emerald-600
      doc.text("ACTION ITEMS", margin + 6, decY);
      decY += 4.5;
    }

    actions.forEach((cleanAct) => {
      const lines = doc.splitTextToSize(cleanAct, contentWidth - 14);
      // Green dot bullet
      doc.setFillColor(16, 185, 129);
      doc.circle(margin + 6.5, decY - 0.9, 1.2, "F");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(20, 83, 45); // emerald-900
      doc.text(lines, margin + 11, decY);
      decY += lines.length * 4.6 + 3;
    });
  }
  y += decCardHeight + 5;

  // 3. KEY QUESTIONS & CONSIDERATIONS (Amber Card Container)
  addSectionHeader("3. Key Questions & Considerations", [245, 158, 11]);
  const questions = getQuestionsList(intelligence);
  const qList = questions.length > 0 ? questions : ["No unresolved blockers or open questions flagged."];

  let qCardHeight = 6;
  qList.forEach((cleanQ) => {
    const lines = doc.splitTextToSize(cleanQ, contentWidth - 14);
    qCardHeight += lines.length * 4.6 + 3;
  });
  checkPageBreak(qCardHeight + 4);

  doc.setFillColor(254, 252, 232); // amber-50
  doc.roundedRect(margin, y, contentWidth, qCardHeight, 2, 2, "F");
  doc.setFillColor(245, 158, 11); // amber-500 left bar
  doc.roundedRect(margin, y, 2.5, qCardHeight, 1, 1, "F");

  let qY = y + 5;
  qList.forEach((cleanQ) => {
    const lines = doc.splitTextToSize(cleanQ, contentWidth - 14);
    // Amber dot bullet
    doc.setFillColor(245, 158, 11);
    doc.circle(margin + 6.5, qY - 0.9, 1.2, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(120, 53, 15); // amber-900
    doc.text(lines, margin + 11, qY);
    qY += lines.length * 4.6 + 3;
  });
  y += qCardHeight + 5;

  // 4. DETAILED DISCUSSION BREAKDOWN (BY TOPIC)
  addSectionHeader("4. Detailed Discussion Breakdown (By Topic)", [79, 70, 229]);
  if (intelligence.detailedTopics && intelligence.detailedTopics.length > 0) {
    intelligence.detailedTopics.forEach((dt) => {
      checkPageBreak(12);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(30, 41, 59); // slate-800
      doc.text(dt.topic, margin, y);
      y += 4.5;

      if (Array.isArray(dt.details)) {
        dt.details.forEach((d) => {
          const cleanD = d.replace(/^[•\s*-]+/, "").trim();
          const lines = doc.splitTextToSize(cleanD, contentWidth - 8);
          checkPageBreak(lines.length * 4.6);
          doc.setFillColor(100, 116, 139); // slate-500
          doc.circle(margin + 2.5, y - 0.8, 0.8, "F");
          doc.setFont("helvetica", "normal");
          doc.setTextColor(51, 65, 85);
          doc.text(lines, margin + 6, y);
          y += lines.length * 4.6 + 1.5;
        });
      }
      y += 2.5;
    });
  } else if (intelligence.analytics?.discussionPhases && intelligence.analytics.discussionPhases.length > 0) {
    intelligence.analytics.discussionPhases.forEach((phase) => {
      checkPageBreak(12);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(30, 41, 59);
      doc.text(`${phase.phaseName || phase.title || phase.phase} (${phase.timeRange})`, margin, y);
      y += 4.5;

      const desc = `Speaker: ${phase.speaker}  |  Outcome: ${phase.outcome}`;
      const lines = doc.splitTextToSize(desc, contentWidth - 6);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(71, 85, 105);
      doc.text(lines, margin + 5, y);
      y += lines.length * 4.6 + 2.5;
    });
  }

  // 5. PIVOTAL AUDIO EVIDENCE & TIMESTAMP ANCHORS
  addSectionHeader("5. Pivotal Audio Evidence & Timestamp Anchors", [99, 102, 241]);
  const moments = intelligence.keyMoments || [];
  if (moments.length > 0) {
    moments.forEach((m) => {
      const spk = m.speaker || "Speaker";
      const lbl = m.topic || m.label || "Key Moment";
      const quoteText = `"${m.quote}"`;
      const quoteLines = doc.splitTextToSize(quoteText, contentWidth - 22);

      let totalMomentHeight = quoteLines.length * 4.6 + 8;
      let sigLines: string[] = [];
      if (m.significance) {
        sigLines = doc.splitTextToSize(m.significance, contentWidth - 26);
        totalMomentHeight += sigLines.length * 4.2 + 4;
      }

      checkPageBreak(totalMomentHeight);

      // Rounded Timestamp Pill
      doc.setFillColor(238, 242, 255); // indigo-50
      doc.roundedRect(margin, y - 3.2, 14, 4.5, 1, 1, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(67, 56, 202); // indigo-700
      doc.text(m.timestamp, margin + 2, y);

      // Speaker & Label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(30, 41, 59); // slate-800
      doc.text(`${spk} (${lbl}):`, margin + 17, y);
      y += 4.5;

      // Quote text
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105); // slate-600
      doc.text(quoteLines, margin + 17, y);
      y += quoteLines.length * 4.6 + 1.5;

      // Significance / Insight (Bulb note)
      if (m.significance && sigLines.length > 0) {
        // Small amber indicator dot (representing the lightbulb)
        doc.setFillColor(245, 158, 11); // amber-500
        doc.circle(margin + 18.5, y - 0.7, 0.9, "F");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.8);
        doc.setTextColor(180, 83, 9); // amber-700
        doc.text("Insight: ", margin + 21, y);

        const insightLabelWidth = doc.getTextWidth("Insight: ");
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 116, 139); // slate-500

        if (sigLines.length === 1 && doc.getTextWidth(m.significance) <= (contentWidth - 22 - insightLabelWidth)) {
          doc.text(m.significance, margin + 21 + insightLabelWidth, y);
          y += 5;
        } else {
          doc.text(sigLines, margin + 21, y + 3.8);
          y += sigLines.length * 4.2 + 4.5;
        }
      } else {
        y += 1.5;
      }
    });
  }

  // 6. FULL DIARIZED TRANSCRIPT
  addSectionHeader("6. Full Diarized Transcript", [100, 116, 139]);
  if (segments.length > 0) {
    segments.forEach((seg) => {
      const mins = Math.floor(seg.start / 60).toString().padStart(2, "0");
      const secs = Math.floor(seg.start % 60).toString().padStart(2, "0");
      const timeStr = `${mins}:${secs}`;
      const spk = seg.speaker || "Speaker";

      // Measure speaker prefix with bold font
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      const spkPrefix = `${spk}: `;
      const spkWidth = doc.getTextWidth(spkPrefix);

      // Measure turn text with normal font
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      const textWidth = doc.getTextWidth(seg.text);
      const maxLineWidth = contentWidth - 18;

      if (spkWidth + textWidth <= maxLineWidth) {
        checkPageBreak(7);
        // Draw Timestamp Pill
        doc.setFillColor(241, 245, 249); // slate-100
        doc.roundedRect(margin, y - 3.2, 13, 4.5, 1, 1, "F");
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139); // slate-500
        doc.text(timeStr, margin + 1.8, y);

        // Draw bold speaker prefix
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8.5);
        doc.setTextColor(30, 41, 59);
        doc.text(spkPrefix, margin + 16, y);

        // Draw normal dialogue text with clean space
        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85);
        doc.text(seg.text, margin + 16 + spkWidth, y);
        y += 5.5;
      } else {
        const fullTurn = `${spkPrefix}${seg.text}`;
        const lines = doc.splitTextToSize(fullTurn, maxLineWidth);
        checkPageBreak(lines.length * 4.6 + 4);

        // Draw Timestamp Pill
        doc.setFillColor(241, 245, 249);
        doc.roundedRect(margin, y - 3.2, 13, 4.5, 1, 1, "F");
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text(timeStr, margin + 1.8, y);

        // Draw bold speaker prefix on line 1
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8.5);
        doc.setTextColor(30, 41, 59);
        doc.text(spkPrefix, margin + 16, y);

        const restOfFirstLine = lines[0].startsWith(spkPrefix)
          ? lines[0].slice(spkPrefix.length)
          : lines[0];
        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85);
        doc.text(restOfFirstLine, margin + 16 + spkWidth, y);
        y += 4.5;

        // Subsequent lines indented under dialogue
        for (let li = 1; li < lines.length; li++) {
          doc.text(lines[li], margin + 16, y);
          y += 4.5;
        }
        y += 1.5;
      }
    });
  } else if (transcript.text) {
    addBodyParagraph(transcript.text);
  }

  // Footer: Running page numbering & confidentiality across all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 12, margin + contentWidth, pageHeight - 12);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text("WhipScribe Audio Intelligence · Executive Briefing", margin, pageHeight - 7.5);
    doc.text(`Page ${i} of ${totalPages}`, margin + contentWidth, pageHeight - 7.5, { align: "right" });
  }

  const filename = generateBriefingPdfFilename(intelligence.title);
  doc.save(filename);
  return filename;
}
